services:
  backend: 
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
  frontend:
    build: ./client
    ports:
        - "3000:80"  
    depends_on:
      - backend